agent_name: mirix
model_name: deepseek-chat
model_endpoint: https://api.deepseek.com/v1
# API密钥从环境变量 DEEPSEEK_API_KEY 读取，请在 .env 文件中配置
model_endpoint_type: openai
generation_config:
  temperature: 1.0
  max_tokens: 8192
  context_window: 64000
