agent_name: mirix
model_name: deepseek-chat
model_endpoint: https://api.deepseek.com/v1
model_endpoint_type: openai
generation_config:
  temperature: 1.0
  max_tokens: 8192
  context_window: 64000
is_screen_monitor: true